### ISSUE TITLE
Implement permalink

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/waba-add-a-bike-lane#14]
From https://github.com/mapbox/waba-add-a-bike-lane/issues/5#issuecomment-349806251: we should implement a permalink, so that users can share the page with a suggested corridor mapped on it. We'll need to figure out the best way to save the drawn geometry – maybe as a data source, or maybe as part of the URL?

/cc @apendleton @joegomez88 @k-mahoney

**Comment by peterqliu** [comment]
🚢
