### ISSUE TITLE
WABA <--> Mapbox

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/waba-add-a-bike-lane#2]
Hi, @WABA-Comms 👋  I'd like you to meet the rest of the Mapbox team that have volunteered for this project: Andrew (@apendleton), Joe (@joegomez88), and Kara (@k-mahoney). 

Colin is the Communications Director at WABA and fellow data enthusiast :) 

I'm excited for us to collaborate together!

**Comment by WABA-Comms** [comment]
Hello everyone! Glad to meet all of you and looking forward to meeting you IRL tomorrow!

**Comment by nickidlugash** [comment]
@WABA-Comms 👋 I'd like you to meet a new volunteer, @peterqliu, who is an awesome designer/developer that will be focusing on front-end development work for this project!

**Comment by WABA-Comms** [comment]
Awesome! Hi Peter! Thanks for joining this project!


Colin Browne
Communications Director
Washington Area Bicyclist Association
colinbrowne@waba.org
(202) 518-0524 x201
waba.org

Are you a card carrying WABA Member? Join or renew today
<http://waba.org/join>!

**Comment by nickidlugash** [comment]
Everyone has been introduced 👋 👋
