### ISSUE TITLE
Geographic extent

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/waba-add-a-bike-lane#3]
@WABA-comms What is the geographic extent that you'd ideally like displayed in the tool? DC proper, or the greater metro DC area (and if so, which specific counties)?

**Comment by WABA-Comms** [comment]
Let's restrict ourselves to the District. Open Data on things like crashes and speeding tickets from the surrounding jurisdictions is inconsistent.

**Comment by nickidlugash** [comment]
Sounds good 👍
