### ISSUE TITLE
Workflow from drawing a line --> returning data

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/waba-add-a-bike-lane#6]
What's the best way to take a user-drawn line on the map (representing a proposed bike lane) and determine which data in our sources are relevant to this corridor? 

Some potentially helpful tools:

- [mapbox-gl-draw plugin](https://github.com/mapbox/mapbox-gl-draw) for mapbox-gl-js, to enable drawing a line ([demo of Mapbox GL Draw here](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/))
- [turf.js](http://turfjs.org/) to calculate what data is relevant to the drawn line
- [querying rendered features](https://www.mapbox.com/mapbox-gl-js/api#map#queryrenderedfeatures) or [source features](https://www.mapbox.com/mapbox-gl-js/api#map#querysourcefeatures)?

/cc @apendleton @joegomez88 @k-mahoney

**Comment by apendleton** [comment]
If we don't want to ship all of the relevant data to the client and do everything client-side, an alternative might be [do the query server-side](https://www.mapbox.com/api-documentation/#retrieve-features-from-mapbox-editor-projects) though it's not entirely clear that we'd get back all the info we'd need in the response.

**Comment by nickidlugash** [comment]
This is done!
